# Generated by Django 5.0 on 2023-12-27 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0002_mood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('NEUTRAL', 'Neutral')], default='HAPPY', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mood',
            unique_together={('user', 'date')},
        ),
    ]
