# Generated by Django 5.0 on 2023-12-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0004_alter_cycle_unique_together_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(default='appointment', max_length=20),
        ),
        migrations.AddField(
            model_name='cycle',
            name='source',
            field=models.CharField(default='cycle', max_length=20),
        ),
        migrations.AddField(
            model_name='mood',
            name='source',
            field=models.CharField(default='mood', max_length=20),
        ),
    ]
