# Generated by Django 5.0 on 2023-12-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0005_appointment_source_cycle_source_mood_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
