# Generated by Django 5.0 on 2023-12-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0006_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
