# Generated by Django 5.0 on 2024-01-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0007_alter_appointment_doctor_alter_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
