# Generated by Django 5.0 on 2024-01-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0009_intercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercourse',
            name='source',
            field=models.CharField(default='intercourse', max_length=20),
        ),
    ]
