# Generated by Django 5.0 on 2024-01-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0010_intercourse_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('medical', 'Medical')], default='medical', max_length=20),
        ),
    ]
