# Generated by Django 5.0 on 2024-01-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealth', '0011_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('WORK', 'Work'), ('PERSONAL', 'Personal'), ('MEDICAL', 'Medical')], default='MEDICAL', max_length=20),
        ),
    ]
